# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
  - pip install -r requirements_test.txt
  - python setup.py install
script:
  - nosetests --rednose --with-cov --cov-config=.coveragerc
after_success:
  - codecov
