# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
  - make install
script:
  - nosetests
after_success:
  - codecov
